INSERT INTO `insurance`.`location` (`id`, `name`) VALUES ('1', '指导科');
INSERT INTO `insurance`.`location` (`id`, `name`) VALUES ('2', '西市场');
INSERT INTO `insurance`.`location` (`id`, `name`) VALUES ('3', '五里沟');
INSERT INTO `insurance`.`location` (`id`, `name`) VALUES ('4', '道德街');
INSERT INTO `insurance`.`location` (`id`, `name`) VALUES ('5', '营市街');
INSERT INTO `insurance`.`location` (`id`, `name`) VALUES ('6', '青年公园');
INSERT INTO `insurance`.`location` (`id`, `name`) VALUES ('7', '中大槐树');
INSERT INTO `insurance`.`location` (`id`, `name`) VALUES ('8', '振兴街');
INSERT INTO `insurance`.`location` (`id`, `name`) VALUES ('9', '南辛庄');
INSERT INTO `insurance`.`location` (`id`, `name`) VALUES ('10', '段店北路');
INSERT INTO `insurance`.`location` (`id`, `name`) VALUES ('11', '匡山');
INSERT INTO `insurance`.`location` (`id`, `name`) VALUES ('12', '张庄路');
INSERT INTO `insurance`.`location` (`id`, `name`) VALUES ('13', '美里湖');
INSERT INTO `insurance`.`location` (`id`, `name`) VALUES ('14', '腊山');
INSERT INTO `insurance`.`location` (`id`, `name`) VALUES ('15', '吴家堡');
INSERT INTO `insurance`.`location` (`id`, `name`) VALUES ('16', '玉清湖');
INSERT INTO `insurance`.`location` (`id`, `name`) VALUES ('17', '兴福');

INSERT INTO `insurance`.`type` (`id`, `category`, `name`) VALUES ('1', '1', '城镇零就业家庭成员的“4050”失业人员');
INSERT INTO `insurance`.`type` (`id`, `category`, `name`) VALUES ('2', '1', '抚养未成年子女单亲家庭成员的 “4050” 失业人员');
INSERT INTO `insurance`.`type` (`id`, `category`, `name`) VALUES ('3', '1', '享受城市居民最低生活保障的“4050”失业人员');
INSERT INTO `insurance`.`type` (`id`, `category`, `name`) VALUES ('4', '1', '持有《中华人民共和国残疾人证》的 “4050” 失业人员');
INSERT INTO `insurance`.`type` (`id`, `category`, `name`) VALUES ('5', '1', '特困家庭未就业的高校毕业生');
INSERT INTO `insurance`.`type` (`id`, `category`, `name`) VALUES ('6', '1', '城镇登记失业的成年后孤儿');
INSERT INTO `insurance`.`type` (`id`, `category`, `name`) VALUES ('7', '2', '城镇零就业家庭成员的“4050”失业人员');
INSERT INTO `insurance`.`type` (`id`, `category`, `name`) VALUES ('8', '2', '抚养未成年子女单亲家庭成员的 “4050” 失业人员');
INSERT INTO `insurance`.`type` (`id`, `category`, `name`) VALUES ('9', '2', '享受城市居民最低生活保障的“4050”失业人员');
INSERT INTO `insurance`.`type` (`id`, `category`, `name`) VALUES ('10', '2', '持有《中华人民共和国残疾人证》的 “4050” 失业人员');
INSERT INTO `insurance`.`type` (`id`, `category`, `name`) VALUES ('11', '2', '特困家庭未就业的高校毕业生');
INSERT INTO `insurance`.`type` (`id`, `category`, `name`) VALUES ('12', '2', '城镇登记失业的成年后孤儿');
INSERT INTO `insurance`.`type` (`id`, `category`, `name`) VALUES ('13', '3', '女性年满40周岁、男性年满50周岁以上且连续失业半年以上的失业人员');
INSERT INTO `insurance`.`type` (`id`, `category`, `name`) VALUES ('14', '3', '城镇零就业家庭成员的“4050”失业人员');
INSERT INTO `insurance`.`type` (`id`, `category`, `name`) VALUES ('15', '3', '抚养未成年子女单亲家庭成员的失业人员');
INSERT INTO `insurance`.`type` (`id`, `category`, `name`) VALUES ('16', '3', '享受城市居民最低生活保障的失业人员');
INSERT INTO `insurance`.`type` (`id`, `category`, `name`) VALUES ('17', '3', '持有《中华人民共和国残疾人证》的失业人员');
INSERT INTO `insurance`.`type` (`id`, `category`, `name`) VALUES ('18', '3', '特困家庭未就业的高校毕业生');
INSERT INTO `insurance`.`type` (`id`, `category`, `name`) VALUES ('19', '3', '城镇登记失业的成年后孤儿');
