INSERT INTO `insurance`.`location` (`id`, `name`) VALUES ('1', '指导科');
INSERT INTO `insurance`.`location` (`id`, `name`) VALUES ('2', '西市场');
INSERT INTO `insurance`.`location` (`id`, `name`) VALUES ('3', '五里沟');
INSERT INTO `insurance`.`location` (`id`, `name`) VALUES ('4', '道德街');
INSERT INTO `insurance`.`location` (`id`, `name`) VALUES ('5', '营市街');
INSERT INTO `insurance`.`location` (`id`, `name`) VALUES ('6', '青年公园');
INSERT INTO `insurance`.`location` (`id`, `name`) VALUES ('7', '中大槐树');
INSERT INTO `insurance`.`location` (`id`, `name`) VALUES ('8', '振兴街');
INSERT INTO `insurance`.`location` (`id`, `name`) VALUES ('9', '南辛庄');
INSERT INTO `insurance`.`location` (`id`, `name`) VALUES ('10', '段店北路');
INSERT INTO `insurance`.`location` (`id`, `name`) VALUES ('11', '匡山');
INSERT INTO `insurance`.`location` (`id`, `name`) VALUES ('12', '张庄路');
INSERT INTO `insurance`.`location` (`id`, `name`) VALUES ('13', '美里湖');
INSERT INTO `insurance`.`location` (`id`, `name`) VALUES ('14', '腊山');
INSERT INTO `insurance`.`location` (`id`, `name`) VALUES ('15', '吴家堡');
INSERT INTO `insurance`.`location` (`id`, `name`) VALUES ('16', '玉清湖');
INSERT INTO `insurance`.`location` (`id`, `name`) VALUES ('17', '兴福');

INSERT INTO `insurance`.`type` (`id`, `category`, `name`) VALUES ('1', '1', '城镇零就业家庭成员的“4050”失业人员');
INSERT INTO `insurance`.`type` (`id`, `category`, `name`) VALUES ('2', '1', '抚养未成年子女单亲家庭成员的 “4050” 失业人员');
INSERT INTO `insurance`.`type` (`id`, `category`, `name`) VALUES ('3', '1', '享受城市居民最低生活保障的“4050”失业人员');
INSERT INTO `insurance`.`type` (`id`, `category`, `name`) VALUES ('4', '1', '持有《中华人民共和国残疾人证》的 “4050” 失业人员');
INSERT INTO `insurance`.`type` (`id`, `category`, `name`) VALUES ('5', '1', '特困家庭未就业的高校毕业生');
INSERT INTO `insurance`.`type` (`id`, `category`, `name`) VALUES ('6', '1', '城镇登记失业的成年后孤儿');
INSERT INTO `insurance`.`type` (`id`, `category`, `name`) VALUES ('7', '2', '城镇零就业家庭成员的“4050”失业人员');
INSERT INTO `insurance`.`type` (`id`, `category`, `name`) VALUES ('8', '2', '抚养未成年子女单亲家庭成员的 “4050” 失业人员');
INSERT INTO `insurance`.`type` (`id`, `category`, `name`) VALUES ('9', '2', '享受城市居民最低生活保障的“4050”失业人员');
INSERT INTO `insurance`.`type` (`id`, `category`, `name`) VALUES ('10', '2', '持有《中华人民共和国残疾人证》的 “4050” 失业人员');
INSERT INTO `insurance`.`type` (`id`, `category`, `name`) VALUES ('11', '2', '特困家庭未就业的高校毕业生');
INSERT INTO `insurance`.`type` (`id`, `category`, `name`) VALUES ('12', '2', '城镇登记失业的成年后孤儿');
INSERT INTO `insurance`.`type` (`id`, `category`, `name`) VALUES ('13', '3', '女性年满40周岁、男性年满50周岁以上且连续失业半年以上的失业人员');
INSERT INTO `insurance`.`type` (`id`, `category`, `name`) VALUES ('14', '3', '城镇零就业家庭成员的“4050”失业人员');
INSERT INTO `insurance`.`type` (`id`, `category`, `name`) VALUES ('15', '3', '抚养未成年子女单亲家庭成员的失业人员');
INSERT INTO `insurance`.`type` (`id`, `category`, `name`) VALUES ('16', '3', '享受城市居民最低生活保障的失业人员');
INSERT INTO `insurance`.`type` (`id`, `category`, `name`) VALUES ('17', '3', '持有《中华人民共和国残疾人证》的失业人员');
INSERT INTO `insurance`.`type` (`id`, `category`, `name`) VALUES ('18', '3', '特困家庭未就业的高校毕业生');
INSERT INTO `insurance`.`type` (`id`, `category`, `name`) VALUES ('19', '3', '城镇登记失业的成年后孤儿');

INSERT INTO `insurance`.`user` (`id`, `lid`, `name`, `weixin`, `login`, `pass`, `state`) VALUES ('1', '1', '王晓蕾', 'WangXiaoLei', 'wangxiaolei', '1', '1');
INSERT INTO `insurance`.`user` (`id`, `lid`, `name`, `weixin`, `login`, `pass`, `state`) VALUES ('2', '1', '王天硕', 'WangTianShuo', 'wangtianshuo', '1', '1');
INSERT INTO `insurance`.`user` (`id`, `lid`, `name`, `weixin`, `login`, `pass`, `state`) VALUES ('3', '1', '张红', 'ZhangHong', 'zhanghong', '1', '1');
INSERT INTO `insurance`.`user` (`id`, `lid`, `name`, `weixin`, `login`, `pass`, `state`) VALUES ('4', '1', '徐心赟', 'XuXinYun', 'xuxinyun', '1', '1');
INSERT INTO `insurance`.`user` (`id`, `lid`, `name`, `weixin`, `login`, `pass`, `state`) VALUES ('5', '2', '类浩阳', 'LeiHaoYang', 'leihaoyang', '2', '1');
INSERT INTO `insurance`.`user` (`id`, `lid`, `name`, `weixin`, `login`, `pass`, `state`) VALUES ('6', '3', '薛海燕', 'XueHaiYan', 'xuehaiyan', '3', '1');
INSERT INTO `insurance`.`user` (`id`, `lid`, `name`, `weixin`, `login`, `pass`, `state`) VALUES ('7', '4', '薛源', 'XueYuan', 'xueyuan', '4', '1');
INSERT INTO `insurance`.`user` (`id`, `lid`, `name`, `weixin`, `login`, `pass`, `state`) VALUES ('8', '5', '苗倩', 'MiaoQian', 'miaoqian', '5', '1');
INSERT INTO `insurance`.`user` (`id`, `lid`, `name`, `weixin`, `login`, `pass`, `state`) VALUES ('9', '6', '庞鹏', 'PangPeng', 'pangpeng', '6', '1');
INSERT INTO `insurance`.`user` (`id`, `lid`, `name`, `weixin`, `login`, `pass`, `state`) VALUES ('10', '7', '王吉延', 'WangJiYan', 'wangjiyan', '7', '1');
INSERT INTO `insurance`.`user` (`id`, `lid`, `name`, `weixin`, `login`, `pass`, `state`) VALUES ('11', '8', '夏倩倩', 'XiaQianQian', 'xiaqianqian', '8', '1');
INSERT INTO `insurance`.`user` (`id`, `lid`, `name`, `weixin`, `login`, `pass`, `state`) VALUES ('12', '9', '扈文骞', 'HuWenQian', 'huwenqian', '9', '1');
INSERT INTO `insurance`.`user` (`id`, `lid`, `name`, `weixin`, `login`, `pass`, `state`) VALUES ('13', '10', '祝天娇', 'ZhuTianJiao', 'zhutianjiao', '10', '1');
INSERT INTO `insurance`.`user` (`id`, `lid`, `name`, `weixin`, `login`, `pass`, `state`) VALUES ('14', '11', '郭瀚阳', 'GuoHanYang', 'guohanyang', '11', '1');
INSERT INTO `insurance`.`user` (`id`, `lid`, `name`, `weixin`, `login`, `pass`, `state`) VALUES ('15', '12', '许珞', 'XuLuo', 'xuluo', '12', '1');
INSERT INTO `insurance`.`user` (`id`, `lid`, `name`, `weixin`, `login`, `pass`, `state`) VALUES ('16', '13', '郑娜', 'ZhengNa', 'zhengna', '13', '1');
INSERT INTO `insurance`.`user` (`id`, `lid`, `name`, `weixin`, `login`, `pass`, `state`) VALUES ('17', '14', '杨琪', 'YangQi', 'yangqi', '14', '1');
INSERT INTO `insurance`.`user` (`id`, `lid`, `name`, `weixin`, `login`, `pass`, `state`) VALUES ('18', '15', '任贵莹', 'RenGuiYing', 'renguiying', '15', '1');
INSERT INTO `insurance`.`user` (`id`, `lid`, `name`, `weixin`, `login`, `pass`, `state`) VALUES ('19', '16', '徐雪珂', 'XuXueKe', 'xuxueke', '17', '1');
INSERT INTO `insurance`.`user` (`id`, `lid`, `name`, `weixin`, `login`, `pass`, `state`) VALUES ('20', '17', '闫海英', 'YanHaiYing', 'yanhaiying', '16', '1');


