package com.wts.entity.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePerson<M extends BasePerson<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setTid(java.lang.Integer tid) {
		set("tid", tid);
	}
	
	public java.lang.Integer getTid() {
		return getInt("tid");
	}

	public void setLid(java.lang.Integer lid) {
		set("lid", lid);
	}
	
	public java.lang.Integer getLid() {
		return getInt("lid");
	}

	public void setCid(java.lang.Integer cid) {
		set("cid", cid);
	}
	
	public java.lang.Integer getCid() {
		return getInt("cid");
	}

	public void setJid(java.lang.Integer jid) {
		set("jid", jid);
	}
	
	public java.lang.Integer getJid() {
		return getInt("jid");
	}

	public void setNumber(java.lang.String number) {
		set("number", number);
	}
	
	public java.lang.String getNumber() {
		return getStr("number");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}
	
	public java.lang.String getName() {
		return getStr("name");
	}

	public void setSex(java.lang.Integer sex) {
		set("sex", sex);
	}
	
	public java.lang.Integer getSex() {
		return getInt("sex");
	}

	public void setBirth(java.util.Date birth) {
		set("birth", birth);
	}
	
	public java.util.Date getBirth() {
		return get("birth");
	}

	public void setPhone(java.lang.String phone) {
		set("phone", phone);
	}
	
	public java.lang.String getPhone() {
		return getStr("phone");
	}

	public void setAddress(java.lang.String address) {
		set("address", address);
	}
	
	public java.lang.String getAddress() {
		return getStr("address");
	}

	public void setBank(java.lang.String bank) {
		set("bank", bank);
	}
	
	public java.lang.String getBank() {
		return getStr("bank");
	}

	public void setCompany(java.lang.String company) {
		set("company", company);
	}
	
	public java.lang.String getCompany() {
		return getStr("company");
	}

	public void setTimeOut(java.util.Date timeOut) {
		set("timeOut", timeOut);
	}
	
	public java.util.Date getTimeOut() {
		return get("timeOut");
	}

	public void setTimeRegist(java.util.Date timeRegist) {
		set("timeRegist", timeRegist);
	}
	
	public java.util.Date getTimeRegist() {
		return get("timeRegist");
	}

	public void setMarriage(java.lang.Integer marriage) {
		set("marriage", marriage);
	}
	
	public java.lang.Integer getMarriage() {
		return getInt("marriage");
	}

	public void setState(java.lang.Integer state) {
		set("state", state);
	}
	
	public java.lang.Integer getState() {
		return getInt("state");
	}

	public void setCheck(java.lang.Integer check) {
		set("check", check);
	}

	public java.lang.Integer getCheck() {
		return getInt("check");
	}

	public void setDelay(java.lang.Integer delay) {
		set("delay", delay);
	}
	
	public java.lang.Integer getDelay() {
		return getInt("delay");
	}

	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}
	
	public java.lang.String getRemark() {
		return getStr("remark");
	}

}
