package com.wts.entity.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSecurity<M extends BaseSecurity<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setLid(java.lang.Integer lid) {
		set("lid", lid);
	}
	
	public java.lang.Integer getLid() {
		return getInt("lid");
	}

	public void setType(java.lang.Integer type) {
		set("type", type);
	}
	
	public java.lang.Integer getType() {
		return getInt("type");
	}

	public void setSfzhm(java.lang.String sfzhm) {
		set("sfzhm", sfzhm);
	}
	
	public java.lang.String getSfzhm() {
		return getStr("sfzhm");
	}

	public void setXm(java.lang.String xm) {
		set("xm", xm);
	}
	
	public java.lang.String getXm() {
		return getStr("xm");
	}

	public void setDwbh(java.lang.String dwbh) {
		set("dwbh", dwbh);
	}
	
	public java.lang.String getDwbh() {
		return getStr("dwbh");
	}

	public void setDwmc(java.lang.String dwmc) {
		set("dwmc", dwmc);
	}
	
	public java.lang.String getDwmc() {
		return getStr("dwmc");
	}

	public void setZjny(java.lang.String zjny) {
		set("zjny", zjny);
	}
	
	public java.lang.String getZjny() {
		return getStr("zjny");
	}

	public void setJfrylb(java.lang.String jfrylb) {
		set("jfrylb", jfrylb);
	}
	
	public java.lang.String getJfrylb() {
		return getStr("jfrylb");
	}

	public void setYlrylb(java.lang.String ylrylb) {
		set("ylrylb", ylrylb);
	}
	
	public java.lang.String getYlrylb() {
		return getStr("ylrylb");
	}

	public void setZglb(java.lang.String zglb) {
		set("zglb", zglb);
	}
	
	public java.lang.String getZglb() {
		return getStr("zglb");
	}

	public void setState(java.lang.Integer state) {
		set("state", state);
	}
	
	public java.lang.Integer getState() {
		return getInt("state");
	}

}
