package com.wts.entity.model;

import com.wts.entity.base.BaseChangefamily;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Changefamily extends BaseChangefamily<Changefamily> {
	public static final Changefamily dao = new Changefamily().dao();
}
