package com.wts.entity.model;

import com.wts.entity.base.BaseChangeperson;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Changeperson extends BaseChangeperson<Changeperson> {
	public static final Changeperson dao = new Changeperson().dao();
}
