package com.wts.entity.model;

import com.wts.entity.base.BaseCommittees;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Committees extends BaseCommittees<Committees> {
	public static final Committees dao = new Committees().dao();
}
