package com.wts.entity.model;

import com.wts.entity.base.BaseCommunity;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Community extends BaseCommunity<Community> {
	public static final Community dao = new Community().dao();
}
