package com.wts.entity.model;

import com.wts.entity.base.BaseFamily;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Family extends BaseFamily<Family> {
	public static final Family dao = new Family().dao();
}
