package com.wts.entity.model;

import com.wts.entity.base.BaseFamilychange;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Familychange extends BaseFamilychange<Familychange> {
	public static final Familychange dao = new Familychange().dao();
}
