package com.wts.entity.model;

import com.wts.entity.base.BaseJob;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Job extends BaseJob<Job> {
	public static final Job dao = new Job().dao();
}
