package com.wts.entity.model;

import com.wts.entity.base.BaseLocation;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Location extends BaseLocation<Location> {
	public static final Location dao = new Location().dao();
}
