package com.wts.entity.model;

import com.wts.entity.base.BasePersonchange;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Personchange extends BasePersonchange<Personchange> {
	public static final Personchange dao = new Personchange().dao();
}
