package com.wts.entity.model;

import com.wts.entity.base.BasePerson;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Person extends BasePerson<Person> {
	public static final Person dao = new Person().dao();
}
