package com.wts.entity.model;

import com.wts.entity.base.BaseSecurity;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Security extends BaseSecurity<Security> {
	public static final Security dao = new Security().dao();
}
