package com.wts.entity.model;

import com.wts.entity.base.BaseSendmessage;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Sendmessage extends BaseSendmessage<Sendmessage> {
	public static final Sendmessage dao = new Sendmessage().dao();
}
