package com.wts.entity.model;

import com.wts.entity.base.BaseType;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Type extends BaseType<Type> {
	public static final Type dao = new Type().dao();
}
